### ISSUE TITLE
When building on Windows64

### ISSUE THREAD

**Issue by shreeswifty** [TheTechnobear/NuiLite#1]
C:\Users\shree\Documents\Pd\externals\NuiLite\build>cmake ../
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.23.28106.4
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
windows not supported at this time
-- Build type: Release
-- Processor: AMD64
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBCAIRO
    linked by target "nuilite" in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite
    linked by target "nuitest" in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite/tests
    linked by target "sidekick" in directory C:/Users/shree/Documents/Pd/externals/NuiLite/sidekick
LIBCAIRO_INC
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite/tests
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite/tests
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/sidekick
LIBFT_INC
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite
   used as include directory in directory C:/Users/shree/Documents/Pd/externals/NuiLite/nuilite/tests

-- Configuring incomplete, errors occurred!
See also "C:/Users/shree/Documents/Pd/externals/NuiLite/build/CMakeFiles/CMakeOutput.log".

**Comment by TheTechnobear** [comment]
NuiLite is only supporting compilation on Norns at this time.
