### ISSUE TITLE
Sidekick search for Pd mother patch

### ISSUE THREAD

**Issue by oxbown** [TheTechnobear/NuiLite#2]

**Comment by oxbown** [comment]
The idea is that Chen a pd patch is selected , sidekick search for a mother patch in /home/we/sidekick/mother.
If it exist, mother.pd will be opened before the pd patch.

And other idea is when button 1 is long pressed sidekick bypass the mother search.

**Comment by TheTechnobear** [comment]
Yeah I considered this, but didn’t really want to start building in too many extras like this into sidekick, which is pretty generic. 
Actually , you can probably already do this, but adding it into the pd-opts.txt file.

**Comment by TheTechnobear** [comment]
It can also be added to the pdopts option in sidekick.json

**Comment by oxbown** [comment]
Ok, i’ll try it! Thank you!

**Comment by oxbown** [comment]
I can confirm that it works!
I made a pd-opts.txt file with a route to mother.pd path, I placed It on sidekick folder and works out of the box.

**Comment by TheTechnobear** [comment]
cool, I'll close for now, as there are two ways to make it work...
but its certainly something I'll keep in mind, I may yet support this in a different way :)
