### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by oxbown** [TheTechnobear/NuiLite#4]
Hi Mark.
First of all, thank you so much for NuiLite.
I´m working doing NornsMother project and I need a couple of more features in Nuilite.

I need "InvertArea" and "Println".
Could you implement these features in NuiLite?

InvertArea (x, y, w, h)
Println(x, y, size,*txtToPrint)

*"Println" needs differents font sizes (like the organelle).

Thank you so much!!!

**Comment by TheTechnobear** [comment]
new api has this
