### ISSUE TITLE
Wiki: bad path in VNC instructions

### ISSUE THREAD

**Issue by okyeron** [TheTechnobear/NuiLite#5]
https://github.com/TheTechnobear/NuiLite/wiki/Using-VNC

`then you can create a small bash script ~/sidekick/System/startvnc.sh`

path should be lowercase `system`? (at least that's what I have on my machine)

**Comment by TheTechnobear** [comment]
yeah, but actually it also needs to be a directory (iirc), 

anyway, Ive just done a 'walkthrough' of the instructions and updated the wiki appropriately. (*)


(*) I'd never bothered with the script part myself ,as i always just started vnc from an ssh shell ... 
so the instructions, were previously just based on a quick post I put on lines previously ;)
